version: "3"

tasks:
  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go

  build:
    desc: Build the app
    cmds:
      - GOGLAGS=-mod=mod go build -o bin/gophersay main.go

  clean:
    desc: Clean the build
    cmds:
      - rm -rf dist
